name: robots_env_cpu
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip

  - numpy=1.26.4
  - scipy
  - matplotlib
  - pyyaml
  - isort<5

  - qpsolvers
  - osqp
  - quadprog

  - pinocchio=2.6.10
  - eigenpy=2.7.14
  - pink

  - pytorch=2.5.1
  - torchvision
  - torchaudio

  - pip:
      - mujoco==2.3.7
      - -e ./src/motion_retargeting
